-- Table Definition ----------------------------------------------

CREATE TABLE IF NOT EXISTS accounts (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username text NOT NULL UNIQUE,
    password text NOT NULL,
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    created_at timestamp without time zone NOT NULL DEFAULT now()
);