CREATE TABLE IF NOT EXISTS orders (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id integer NOT NULL,   
    driver_id integer NULL,   
    estimated_price integer NOT NULL,   
    distance integer NOT NULL,   
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),

    CONSTRAINT fk_client_id FOREIGN KEY(client_id) REFERENCES clients(id)
    CONSTRAINT fk_driver_id FOREIGN KEY(driver_id) REFERENCES drivers(id)
);

CREATE TABLE IF NOT EXISTS orders_locations (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id integer NOT NULL,   
    location_name text NULL DEFAULT '',
    longitude float NOT NULL,
    latitude float NOT NULL, 
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),

    CONSTRAINT fk_order_id FOREIGN KEY(order_id) REFERENCES orders(id)
);